### ISSUE TITLE
Generator Roadmap

### ISSUE THREAD

**Issue by andrewconnell** [andrewconnell/generator-nodehttps#1]
In an effort to be as transparent as possible, this roadmap will list the plans for this generator.
## Priority 1
- [x] Publishing initial release that creates the Node.js `server.js` with a static page & CSS file to host locally via HTTPS on a specified port (ie: `https://localhost:8443`).
## Priority 2
- [x] Add tests
- [x] Setup travis
- [ ] Convert to TypeScript
## Priority 3
- [ ] Prompt user for existing SSL cert & key to use
- [ ] Prompt user to create a self-signed SSL cert & key; have generator create the key
- [ ] Have generator programmatically trust self-signed cert
## Priority 4
- [ ] Add support for MVC & HBS

If you think there are other things that should be added to the roadmap, or have questions about any of these, please feel free to comment.
